---
- name: Install Cisco VPN and Kerberos clients
  package:
    name:
    - vpnc
    - network-manager-vpnc-gnome
    - heimdal-clients
    state: present

- name: Install $HOME/.krb5.conf.{{ secrets.customer1.name }}
  copy:
    src: files/customer1/krb5.conf
    dest: "{{ actual_home }}/.krb5.conf.{{ secrets.customer1.name }}"
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0600

- name: Install $HOME/bin/kinit-{{ secrets.customer1.name }}.sh
  copy:
    src: files/customer1/kinit.sh
    dest: "{{ actual_home }}/.local/bin/kinit-{{ secrets.customer1.name }}.sh"
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0700

- name: Install /etc/vpnc/{{ secrets.customer1.name }}.conf
  copy:
    src: files/customer1/vpnc.conf
    dest: /etc/vpnc/{{ secrets.customer1.name }}.conf
    owner: root
    group: root
    mode: 0600
