- name: Install AWS CLI and Boto
  package: name={{ item }} state=present
  with_items:
    - awscli
    - aws-shell
    - python-boto
    - python-boto3
    - python3-boto
    - python3-boto3
    - s3cmd

- name: Remove snap aws-cli
  shell: snap remove {{ item }} --no-wait
  with_items:
    - aws-cli

- name: Create AWS config directory
  file:
    path: {{ actual_home }}/.aws
    state: directory
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0755

- name: Configure AWS CLI profiles
  ini_file:
    dest: {{ actual_home }}/.aws/config
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0644
    section: "{{ item.s }}"
    option: "{{ item.k }}"
    value: "{{ item.v }}"
    backup: yes
  with_items:
  - { s: 'profile hit', k: region, v: eu-west-1 }
  - { s: 'profile crisp', k: region, v: eu-central-1 }
  - { s: 'profile codekvast', k: region, v: eu-central-1 }
  - { s: 'profile {{ secrets.customer4.name }}', k: region, v: eu-west-1 }
  notify: Test AWS CLI
  loop_control:
    label: "[{{ item.s }}] {{ item.k }}={{ item.v }}"

- name: Configure AWS CLI credentials
  ini_file:
    dest: {{ actual_home }}/.aws/credentials
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0600
    section: "{{ item.s }}"
    option: "{{ item.k }}"
    value: "{{ item.v }}"
    backup: yes
  with_items:
  - { s: 'hit', k: 'aws_access_key_id', v: "{{ secrets.aws.hit.access_key }}" }
  - { s: 'hit', k: 'aws_secret_access_key', v: "{{ secrets.aws.hit.secret_key }}" }
  - { s: 'codekvast', k: 'aws_access_key_id', v: "{{ secrets.aws.hit.access_key }}" }
  - { s: 'codekvast', k: 'aws_secret_access_key', v: "{{ secrets.aws.hit.secret_key }}" }
  - { s: 'crisp', k: 'aws_access_key_id', v: "{{ secrets.aws.crisp.access_key }}" }
  - { s: 'crisp', k: 'aws_secret_access_key', v: "{{ secrets.aws.crisp.secret_key }}" }
  - { s: "{{ secrets.customer4.name }}", k: 'aws_access_key_id', v: "{{ secrets.aws.customer4.access_key }}" }
  - { s: "{{ secrets.customer4.name }}", k: 'aws_secret_access_key', v: "{{ secrets.aws.customer4.secret_key }}" }
  notify: Test AWS CLI
  loop_control:
    label: "[{{ item.s }}] {{ item.k }}=xxxxxxxx"

- name: Configure Boto profiles
  ini_file:
    dest: {{ actual_home }}/.boto
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0600
    section: "{{ item.s }}"
    option: "{{ item.k }}"
    value: "{{ item.v }}"
    backup: yes
  with_items:
  - { s: 'hit', k: 'aws_access_key_id', v: "{{ secrets.aws.hit.access_key }}" }
  - { s: 'hit', k: 'aws_secret_access_key', v: "{{ secrets.aws.hit.secret_key }}" }
  - { s: 'codekvast', k: 'aws_access_key_id', v: "{{ secrets.aws.hit.access_key }}" }
  - { s: 'codekvast', k: 'aws_secret_access_key', v: "{{ secrets.aws.hit.secret_key }}" }
  - { s: 'crisp', k: 'aws_access_key_id', v: "{{ secrets.aws.crisp.access_key }}" }
  - { s: 'crisp', k: 'aws_secret_access_key', v: "{{ secrets.aws.crisp.secret_key }}" }
  - { s: "{{ secrets.customer4.name }}", k: 'aws_access_key_id', v: "{{ secrets.aws.customer4.access_key }}" }
  - { s: "{{ secrets.customer4.name }}", k: 'aws_secret_access_key', v: "{{ secrets.aws.customer4.secret_key }}" }
  notify: Test AWS CLI
  loop_control:
    label: "[{{ item.s }}] {{ item.k }}=xxxxxxxx"

- name: Create $HOME/.s3cfg
  template:
    src: s3cfg.j2
    dest: {{ actual_home }}/.s3cfg
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0600
