---
- name: Install Calibre
  package: name=calibre state=present

- name: Create Calibre config directory
  file:
    path: "{{ actual_home }}/.config/calibre"
    state: directory
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0755

- name: Customize Calibre library path
  lineinfile:
    dest: "{{ actual_home }}/.config/calibre/global.py"
    regexp: ^library_path.*
    line: "library_path = u'{{ actual_home }}/Dropbox/Calibre-jobb'"
    backup: yes

- name: Customize Calibre SMTP
  template:
    src: calibre-smtp.py
    dest: "{{ actual_home }}/.config/calibre/smtp.py"
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0600
    backup: yes

- name: Customize Calibre DeDRM plugin
  template:
    src: calibre-dedrm.json
    dest: "{{ actual_home }}/.config/calibre/plugins/dedrm.json"
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0600
    backup: yes
