---

- name: Add Charles Proxy APT keys
  apt_key: id=1AD28806 keyserver=hkp://pgp.mit.edu:80

- name: Add Charles Proxy APT source
  apt_repository:
    filename: charles
    repo: "deb https://www.charlesproxy.com/packages/apt/ charles-proxy main"

- name: Install Charles Proxy
  package: name=charles-proxy state=present

- name: Install $HOME/.charles.config (if missing)
  template:
    src: charles.config
    dest: "{{ actual_home }}/.charles.config"
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0600
    force: no
