---
- name: Install/uninstall OpenJDK
  package: name="openjdk-{{ item[0].version }}-{{ item[1] }}" state="{{ item[0].state }}"
  with_nested:
  - [ {version: 8, state: absent}, {version: 11, state: absent }]
  - [ jdk, jdk-headless, jre, jre-headless, source, doc ]
  ignore_errors: yes

- name: Install git and curl
  package:
    name:
    - git
    - curl
    state: present

- name: git config --global credential.helper store
  shell: git config --global credential.helper store

- name: Uninstall nodejs-legacy and npm
  package:
    name:
    - nodejs-legacy
    - npm
    state: absent

- name: Fetch NodeJS APT source script
  get_url: url=https://deb.nodesource.com/setup_12.x dest=/tmp/nodesource_setup_12.x.sh mode=0755

- name: Execute NodeJS APT source script
  shell: /tmp/nodesource_setup_12.x.sh # creates=/etc/apt/sources.list.d/nodesource.list
  ignore_errors: yes # TODO: Does not support Eoan yet

- name: Install NodeJS
  apt:
    name:
    - nodejs
    - build-essential
    state: latest
    update_cache: yes

- name: Remove phantomjs-prebuilt from /usr/local
  file: path={{ item }} state=absent
  with_items:
  - /usr/local/lib/node_modules/phantomjs-prebuilt
  - /usr/local/bin/phantomjs

- name: Install gradlew finder
  template: src=gradlew-finder.sh dest=/usr/local/bin/gradlew mode=a=rx

- name: Remove old gradlew finder
  file: path=/usr/local/bin/gradle state=absent

- name: Install Python3
  package: name=python3 state=present

- name: Install pip3
  package: name=python3-pip state=present

- name: Make Python3 default
  alternatives:
    name: "{{ item }}"
    link: "/usr/bin/{{ item }}"
    path: "/usr/bin/{{ item }}3"
  with_items:
    - python
    - pip

- name: Remove Python2
  package: name=python2.7 state=absent
