---
- name: Add Erlang Solutions APT key
  apt_key: url=https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc state=present

- name: Add Erlang Solutions APT source
  apt_repository:
    filename: erlang
    repo: "deb https://packages.erlang-solutions.com/ubuntu {{ distribution_release | default(ansible_distribution_release) }} contrib"
    state: present

- name: Install Erlang
  package:
    name:
    - esl-erlang
    - elixir
    state: present
