---
- set_fact:
    sdkman_dir: "{{ lookup('env', 'HOME')}}/.sdkman"
    fish_config_dir: "{{ lookup('env', 'HOME')}}/.config/fish"

- name: Install Fish & pip3
  package:
    name:
    - fish
    - thefuck
    - python3-dev
    - python3-pip
    state: present

- name: Set Fish as login shell
  user: name={{ actual_username }} shell=/usr/bin/fish

- name: Create Fish config directories
  file: dest={{ fish_config_dir }}/{{ item }} state=directory
  with_items:
  - functions
  - completions

- name: Install Fish functions and completions
  copy:
    src: files/fish/{{ item }}
    dest: "{{ fish_config_dir }}/{{ item }}"
  with_items:
  - completions/aws.fish
  - completions/docker.fish
  - completions/sdk.fish
  - functions/fish_prompt.fish
  - functions/fuck.fish
  - functions/mkd.fish
  - functions/sdk.fish

- name: Set correct ownership of {{ fish_config_dir }}
  file: dest={{ fish_config_dir }} owner={{ actual_username }} group={{ actual_username }} recurse=yes
