---
- name: Install misc utilities
  package: name="{{ item }}" state=present
  with_items:
    - ack
    - compizconfig-settings-manager
    - curl
    - dconf-cli
    - encfs
    - gnome-gmail
    - gpg
    - jq
    - libimage-exiftool-perl
    - nixnote2
    - oathtool
    - openssh-server
    - synaptic
    - tree
    - unzip
    - wget
    - xemacs21

- name: Remove obsolete apt packages
  package: name="{{ item }}" state=absent
  with_items:
    - indicator-cpufreq
    - keepassxc

- name: Install snaps
  snap: name="{{ item }}" state=present
  with_items:
    - keepassxc
    - postman

- name: Start sshd
  service: name=ssh state=started enabled=yes

- name: Create $HOME/.local/bin
  file:
    path: "{{ actual_home }}/.local/bin"
    state: directory
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0755

- name: Link $HOME/.local/bin to $HOME/bin
  file: src={{ actual_home }}/.local/bin dest={{ actual_home }}/bin state=link

- name: Install stuff in $HOME/.local/bin
  template:
    src: "{{ item }}"
    dest: "{{ actual_home }}/.local/bin/{{ item }}"
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0755
  with_items:
    - mfa.sh

- name: Create $HOME/.gradle
  file:
    path: "{{ actual_home }}/.gradle"
    state: directory
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 755

- name: Import Codekvast GPG keypair
  shell: gpg --import {{ item }}
  ignore_errors: yes
  with_items:
    - vars/codekvast.gpg.pub
    - vars/codekvast.gpg.priv

- name: Edit $HOME/.gradle/gradle.properties
  blockinfile:
    dest: "{{ actual_home }}/.gradle/gradle.properties"
    create: yes
    backup: yes
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0600
    block: |
      codekvast.bintray.user={{ secrets.bintray.user }}
      codekvast.bintray.key={{ secrets.bintray.key }}

      codekvast.gpg.keyId={{ secrets.codekvast.gpg.keyId }}
      codekvast.gpg.password={{ secrets.codekvast.gpg.password }}
      codekvast.gpg.secretKeyRingFile={{ actual_home }}/.gnupg/codekvast.kbx
