---
- name: Install misc utilities
  package:
    name:
    - ack
    - compizconfig-settings-manager
    - curl
    - dconf-cli
    - emacs25
    - encfs
    - gnome-gmail
    - indicator-cpufreq
    - jq
    - keepassx
    - libimage-exiftool-perl
    - nautilus-dropbox
    - nixnote2
    - openssh-server
    - synaptic
    - tree
    - unzip
    - wget
    state: present

- name: Start sshd
  service: name=sshd state=started enabled=yes

- name: Create $HOME/.local/bin
  file:
    path: "{{ lookup('env', 'HOME')}}/.local/bin"
    state: directory
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0755

- name: Create $HOME/.gradle
  file:
    path: "{{ lookup('env', 'HOME') }}/.gradle"
    state: directory
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 755

- name: Edit $HOME/.gradle/gradle.properties
  blockinfile:
    dest: "{{ lookup('env', 'HOME') }}/.gradle/gradle.properties"
    create: yes
    backup: yes
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0600
    block: |
      org.gradle.daemon=true

      bintrayUser={{ secrets.bintray.user }}
      bintrayKey={{ secrets.bintray.key }}

      {{ secrets.customer2.name }}ArtifactoryUser={{ secrets.customer2.artifactory.user}}
      {{ secrets.customer2.name }}ArtifactoryPwd={{ secrets.customer2.artifactory.pwd}}
      {{ secrets.customer2.name }}ArtifactoryContext={{ secrets.customer2.artifactory.context}}
