---
- name: Add SBT APT key
  apt_key:
    id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    keyserver: hkp://keyserver.ubuntu.com:80

- name: Add SBT APT source
  apt_repository:
    filename: sbt
    repo: "deb https://dl.bintray.com/sbt/debian /"

- name: Install Scala compiler and SBT
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - scala
    - sbt
