---
  
- name: Install Vagrant and system-wide plugins
  package:
    name:
    - vagrant
    - vagrant-cachier
    state: present

- name: Install user-specific Vagrant plugins
  command: vagrant plugin install {{ item }} creates="{{ actual_home }}/.vagrant.d/gems/specifications/{{ item }}-*.gemspec"
  with_items:
  - vagrant-hostmanager
  - vagrant-vbguest

- name: Set correct ownership of $HOME/{{ item }}/**
  file: dest={{ actual_home }}/{{ item }} owner={{ actual_username }} group={{ actual_username }} state=directory recurse=yes
  with_items:
  - .bundle
  - .vagrant.d
  - .gem

