---
- name: Define distribution release
  set_fact: distribution_release=focal

- name: Add VirtualBox APT key
  apt_key: url={{ item }} state=present
  with_items:
  - https://www.virtualbox.org/download/oracle_vbox.asc
  - https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Define VirtualBox APT source
  apt_repository:
    filename: virtualbox
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ distribution_release | default(ansible_distribution_release) }} contrib"
    state: present

- name: Install VirtualBox
  package:
    name:
    - virtualbox
    - virtualbox-ext-pack
    - virtualbox-guest-additions-iso
    - virtualbox-qt
    state: present
