---
- name: Install handler for ssh:// links
  copy:
    src: ssh.desktop
    dest: "{{ actual_home }}/.local/share/applications/ssh.desktop"
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0644
  notify: xdg-mime default ssh.desktop x-scheme-handler/ssh

- name: Install handler for geo:// links
  template:
    src: "{{ item }}"
    dest: "{{ actual_home }}/.local/{{item.d}}/{{ item.s }}"
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    mode: 0644
  notify: xdg-mime default google-maps-geo.desktop x-scheme-handler/geo
  with_items:
    - {s: google-maps-geo.desktop, d: share/applications}
    - {s: loupe-maps-bridge.desktop, d: bin}

