---
- name: Install sonic-token.sh
  template:
     src: customer4/sonic-token.sh
     dest: "{{ lookup('env', 'HOME')}}/.local/bin/sonic-token.sh"
     mode: 0755
     owner: "{{ actual_username }}"
     group: "{{ actual_username }}"

- name: Install ~/.m2/settings.xml
  template:
    src: customer4/m2-settings.xml
    dest: "{{ lookup('env', 'HOME')}}/.m2/settings.xml"
    mode: 0755
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    backup: yes

- name: Install Postman
  command: snap install postman
  args:
     creates: /snap/bin/postman
