---
- name: Remove obsolete auth scripts
  file:
     path: "{{ actual_home }}/.local/bin/{{ item }}"
     state: absent
  with_items:
    - "{{ secrets.customer4.product }}-token.sh"

- name: "Create $HOME/./aws/{{ secrets.customer4.product }}.mfa"
  copy:
    dest: "{{ actual_home }}/.aws/{{ secrets.customer4.name }}.mfa"
    content: "{{ secrets.customer4.mfa_base }}"
    mode: 0600
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"

- name: Install ~/.m2/settings-discocloud.xml
  template:
    src: customer4/m2-settings-discocloud.xml
    dest: "{{ actual_home }}/.m2/settings-discocloud.xml"
    mode: 0755
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    backup: yes

- name: Install ~/.m2/m2-settings-boltcloud.xml
  template:
    src: customer4/m2-settings-boltcloud.xml
    dest: "{{ actual_home }}/.m2/settings-boltcloud.xml"
    mode: 0755
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"
    backup: yes

- name: Make Artifactory default
  file:
    src: "{{ actual_home }}/.m2/settings-boltcloud.xml"
    dest: "{{ actual_home }}/.m2/settings.xml"
    state: link
    mode: 0755
    owner: "{{ actual_username }}"
    group: "{{ actual_username }}"

- name: Install Postman
  snap: name=postman state=present

- name: Install Gimme AWS Creds
  command: pip3 install --upgrade gimme-aws-creds

- name: Increase vm.max_map_count for ElasticSearch in Docker
  template: src=sysctl/90-elasticsearch.conf dest=/etc/sysctl.d/90-elasticsearch.conf
  notify: sysctl --system

- set_fact:
    aws_ssm_plugin: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb
    aws_ssm_plugin_local: "/tmp/aws-session-manager-plugin.deb"

- name: Download AWS Session Manager Plugin
  get_url:
    url: "{{ aws_ssm_plugin }}"
    dest: "{{ aws_ssm_plugin_local }}"
    mode: 0755

- name: Install AWS Session Manager Plugin
  shell: dpkg -i {{ aws_ssm_plugin_local }}

- name: Install Krew
  shell:
    cmd: HOME="{{ actual_home }}" files/customer4/install-krew.sh
    creates: "{{ actual_home }}/.krew/bin"

- name: Change owner of Krew
  file:
     path: "{{ actual_home }}/.krew"
     state: directory
     recurse: true
     mode: 0755
     owner: "{{ actual_username }}"
     group: "{{ actual_username }}"
