---
- hosts: all
  connection: local
  become: yes
  vars:
  - docker_compose_version: 1.21.2
  - docker_machine_version: 0.14.0
  - intellij_version: 183.2407.10
  - intellij_version_name: "{{ intellij_version }}"
  - intellij_checksum: "sha256:29ec8ea94a331fc7fd6a89120e3f436952e5558ce178910d1be5071c4fdcb2fa"
  - intellij_archive: ideaIU-{{ intellij_version_name }}-no-jdk.tar.gz
  vars_files:
  - vars/secrets.yml

  handlers:
  - import_tasks: handlers/main.yml

  tasks:
  - {import_tasks: tasks/root-password.yml, tags: aws}
  - {import_tasks: tasks/aws-cli.yml, tags: aws}
  - {import_tasks: tasks/calibre.yml, tags: calibre}
  - {import_tasks: tasks/charles-proxy.yml, tags: [charles-proxy, charles]}
  - {import_tasks: tasks/compilers.yml, tags: [compilers, codekvast]}
  - {import_tasks: tasks/docker.yml, tags: [docker, codekvast]}
  - {import_tasks: tasks/fish.yml, tags: [fish, sdkman]}
  - {import_tasks: tasks/google-chrome.yml, tags: [chrome, google-chrome]}
  - {import_tasks: tasks/heroku-toolbelt.yml, tags: [heroku, codekvast]}
  - {import_tasks: tasks/intellij.yml, tags: [intellij, idea, codekvast]}
  - {import_tasks: tasks/misc.yml, tags: misc}
  - {import_tasks: tasks/nfs-mounts.yml, tags: [fstab, nfs, nfs-mounts]}
  - {import_tasks: tasks/scala.yml, tags: [compilers, scala]}
  - {import_tasks: tasks/spotify.yml, tags: spotify}
  - {import_tasks: tasks/vagrant.yml, tags: vagrant}
  - {import_tasks: tasks/virtualbox.yml, tags: virtualbox}
  - {import_tasks: tasks/yarn.yml, tags: yarn}
