---
- hosts: all
  connection: local
  become: yes
  vars:
  - docker_compose_version: 1.23.2
  - docker_machine_version: 0.16.0
  - intellij_version: 192.4488.21
  - intellij_version_name: "{{ intellij_version }}"
  - intellij_checksum: "sha256:e73d7be40793312cd35c7bb565b805465d973f3cca619a26bc9e192dc5e4288e"
  - intellij_archive: ideaIU-{{ intellij_version_name }}.tar.gz
  - sdkman_install_packages:
    - { candidate: java, version: '11.0.1-open' }
    - { candidate: java, version: '8.0.192-zulu' }
    - { candidate: java, version: '7.0.201-zulu' }
  - sdkman_defaults:
      java: '8.0.192-zulu'
  - slack_version: 3.4.2
  - slack_archive: https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb

  vars_files:
  - vars/secrets.yml

  handlers:
  - import_tasks: handlers/main.yml

  roles:
  - {role: comcast.sdkman, tags: sdkman}

  post_tasks:
  - {import_tasks: tasks/root-password.yml, tags: aws}
  - {import_tasks: tasks/aws-cli.yml, tags: aws}
  - {import_tasks: tasks/calibre.yml, tags: calibre}
  - {import_tasks: tasks/charles-proxy.yml, tags: [charles-proxy, charles]}
  - {import_tasks: tasks/compilers.yml, tags: [compilers, codekvast]}
  - {import_tasks: tasks/docker.yml, tags: [docker, codekvast]}
  - {import_tasks: tasks/fish.yml, tags: [fish]}
  - {import_tasks: tasks/google-chrome.yml, tags: [chrome, google-chrome]}
  - {import_tasks: tasks/heroku-toolbelt.yml, tags: [heroku, codekvast]}
  - {import_tasks: tasks/intellij.yml, tags: [intellij, idea, codekvast]}
  - {import_tasks: tasks/misc.yml, tags: misc}
  - {import_tasks: tasks/nfs-mounts.yml, tags: [fstab, nfs, nfs-mounts]}
  - {import_tasks: tasks/scala-remove.yml, tags: [compilers, scala]}
  - {import_tasks: tasks/slack.yml, tags: slack}
  - {import_tasks: tasks/spotify.yml, tags: spotify}
  - {import_tasks: tasks/vagrant.yml, tags: vagrant}
  - {import_tasks: tasks/virtualbox.yml, tags: virtualbox}
  - {import_tasks: tasks/yarn.yml, tags: yarn}
